### PR TITLE
update guide to mphealth 2.2

### PR DESCRIPTION
**Pull request by DannyS03**
https://github.com/openliberty/guide-microprofile-health/issues/108

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
@DannyS03 
- [ ] in finish/system/src/main/java/io/openliberty/guides/system/SystemReadinessCheck.java, extra space char in each line

**Comment by gkwan-ibm** [comment]
@DannyS03 
- [ ] suggest `SystemResource.class.getSimpleName() + " Readiness Check"` install of `isAlive`
- [ ] make sure both readiness and liveness check do same 
- [ ] make sure the inventory health checks do the same
- [ ] make sure finish and start do the same

**Comment by gkwan-ibm** [comment]
@DannyS03 
- [ ] InventoryReadinessCheck.java
  - `import org.eclipse.microprofile.health.HealthCheckResponseBuilder;` is not needed, right?
  -  some space lines are not needed

**Comment by DannyS03** [comment]
- tested/verified on **qa**.
  - https://github.com/OpenLiberty/guide-kubernetes-microprofile-health/pull/85

**Pull request merged**
